---
booktitle: Proceedings of 2018 ACM SIGKDD Workshop on Causal Discovery
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 2640-3498
volume: 92
published: 2018-08-09
year: '2018'
shortname: CD
url: http://proceedings.mlr.press
start: 2018-08-20
end: 2018-08-20
layout: proceedings
id: CD2018
month: 0
cycles: false
editor:
- given: Thuc Duy
  family: Le
- given: Kun
  family: Zhang
- given: Emre
  family: Kıcıman
- given: Aapo
  family: Hyvärinen
- given: Lin
  family: Liu
title: Proceedings of Machine Learning Research
description: |
  Proceedings of 2018 ACM SIGKDD Workshop on Causal Discovery
    Held in London, UK on 20 August 2018

  Published as Volume 92 by the Proceedings of Machine Learning Research on 09 August 2018.

  Volume Edited by:
    Thuc Duy Le
    Kun Zhang
    Emre Kıcıman
    Aapo Hyvärinen
    Lin Liu

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 20 Aug
baseurl: "/v92"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v92
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Proceedings of 2018 ACM SIGKDD Workshop on Causal Discovery
  url: 
  location: London, UK
  dates:
  - 2018-08-20
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
